version: "3"

services:
  mysqldb:
    image: mysql:5
    networks:
      - fleetman-network
    environment:
      MYSQL_ROOT_PASSWORD: padaria123
      MYSQL_DATABASE: fleetman

  fleetman-webapp:
    image: lazoski/fleetman8
    networks:
      - fleetman-network
    ports:
      - 80:8080
    depends_on:
      - mysqldb

networks:
  fleetman-network: