version: "3"

services:
  database:
    image: mysql:5
    networks:
      - fleetman-network
    volumes:
      - //d/docker/mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: padaria123
      MYSQL_DATABASE: fleetman

  fleetman-webapp:
    image: lazoski/fleetman8
    networks:
      - fleetman-network
    ports:
      - 80:8080
    depends_on:
      - database

networks:
  fleetman-network: